//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Symptoms = new HashSet<Symptom>();
        }
    
        public int PatientID { get; set; }
        public string PatientName { get; set; }
        public string PatientAddress { get; set; }
        public Nullable<int> PatientAge { get; set; }
        public string PatientGender { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<int> PatientContact { get; set; }
        public Nullable<int> WardID { get; set; }
        public Nullable<int> PatientRoomNo { get; set; }
        public Nullable<int> DoctorID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Ward Ward { get; set; }
        public virtual ICollection<Symptom> Symptoms { get; set; }
    }
}
