//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptom
    {
        public int SymptomID { get; set; }
        public string Symp { get; set; }
        public Nullable<int> PatientID { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
